Back/index.js
=> index creacion

Back/src/db.js
=> base de datos

Back/src/Models/subCategorias.js
=> Modelo sub categoria

Back/src/Models/Categorias.js
creacion del modelo de categorias
=> Modelo categorias

Back/src/Models/Usuarios.js
=> Model usuarios

client/src/VitalFitApp.jsx, client/src/components/Card/Card.jsx, client/src/components/Card/Card.module.css, client/src/components/NavBarComp.jsx, client/src/components/productsPage/ProductsPage.jsx, client/src/components/productsPage/ProductsPage.module.css, client/src/routes/AppRouter.jsx, client/src/routes/MainRouter.jsx, node_modules/.yarn-integrity
=> productPage

Back/src/Handlers/User/postUserHandler.js, Back/src/data.json
=> Json para el front

client/src/VitalFitApp.jsx, client/src/components/Card/Card.jsx, client/src/components/DetailCard/Detail.jsx, client/src/routes/AppRouter.jsx
=> feat: add product detail

client/package.json, client/src/api/productsInstance.js, client/src/components/DetailCard/Detail.jsx, client/src/components/NavBarComp.jsx, client/src/components/OrderModal.jsx, client/src/components/index.js, client/src/components/productsPage/ProductsPage.jsx, client/src/icons/CloseIcon.jsx, client/src/icons/index.js, client/src/index.css, client/src/store/slices/index.js, client/src/store/slices/orders/index.js, client/src/store/slices/orders/orderSlice.js, client/src/store/slices/orders/thunks.js, client/src/store/slices/products/productSlice.js, client/src/store/slices/products/thunks.js, client/src/store/store.js, client/tailwind.config.js, client/yarn.lock
Redux retoques, y modal de productos en el carrito
=> redux and order modal

Back/src/Controllers/Products/deleteProduct.js, Back/src/Handlers/Products/deleteProductHandler.js, Back/src/Routes/index.js
Controller - handler y ruta para eliminar productos
=> Deleted products

Back/src/Controllers/Products/activarDesactivarProduct.js, Back/src/Handlers/Products/activarDesactivarHandler.js, Back/src/Models/Product.js, Back/src/Routes/index.js, Back/src/utils/postManyProductsController.js
Avtivado y desactivado de producto
=> Disable product

client/src/components/Calification/index.jsx, client/src/components/CardsProducts/CardsProducts.jsx, client/src/components/DetailCard/Detail.jsx, client/src/components/index.js
Detalle del producto finalizado.
=> finish detail-card

.env, Back/src/Controllers/Order/getOrderController.js, Back/src/Controllers/Order/postOrderController.js, Back/src/Handlers/Order/getOrderHandler.js, Back/src/Handlers/Order/postOrderHandler.js
=> creacion de controllers order

Back/src/Controllers/Products/getProductController.js, Back/src/Handlers/Products/getProductsHandler.js, Back/src/Routes/index.js, package-lock.json
=> Filter controller

client/src/components/FooterComp.jsx, client/src/firebase/config.js, client/src/firebase/providers.js, client/src/routes/AppRouter.jsx, client/src/store/slices/auth/authSlice.js, client/src/store/slices/auth/index.js, client/src/store/slices/auth/thunks.js, client/src/store/slices/index.js
Se creo la funcionalidad de los usuarios con firebase, se maneja todo desde el slice, y la configuración se alamacenó en la carpeta de firebase. Se corrigió el error con del footer en el login
=> auth changes and fixed footer on login

client/src/components/Card/Card.jsx, client/src/components/Card/Card.module.css, client/src/components/ItemsAdded.jsx, client/src/components/ItemsCheckoutList.jsx, client/src/components/NavBarComp.jsx, client/src/components/OrderModal.jsx, client/src/components/ProcessOrder.jsx, client/src/components/TotalPrice.jsx, client/src/components/index.js, client/src/components/productsPage/ProductsPage.module.css, client/src/index.css, client/src/pages/ProductsPage.jsx, client/src/store/slices/products/thunks.js
Shopping flow implemented, falta completarlo con el mercado pago, e implementar otro modal que muestre los métodos de pago. Se corrigió un detalle de estilo en la página de productos, y se implemento de igual manera el agregar productos al carrito con su respectivo contador en el nav bar. Se me olvidó agregar el order filter, pero ya esta listo
=> shop flow and productsPage details

.env, Back/src/Controllers/Category/getCategory.js, Back/src/Controllers/Products/getProductController.js, Back/src/Handlers/Category/getCategoryHandler.js, Back/src/Handlers/Products/activarDesactivarHandler.js, Back/src/Handlers/Products/getProductsHandler.js, client/src/components/Filter/Filter.jsx, client/src/pages/ProductsPage.jsx, client/src/store/slices/products/productSlice.js, client/src/store/slices/products/thunks.js
Componente de filtrado desde el back, cambiando el filtrado previamente realizado desde el front por el componente Filter, agregué parámetros de búsqueda a la request get de los productos, y al estado inicial agregué los parámetros de filtrado, ordenamiento y búsqueda
=> Filter back

Back/src/db.js, client/src/components/Filter/Filter.jsx
Configuración de back para el deploy de base de datos, limpiado de funciones del componente filter
=> Deploy database

client/src/components/Cart/Cart.jsx, client/src/components/Cart/CartButton/CartButton.jsx, client/src/components/Cart/Order.jsx, client/src/components/NavBarComp.jsx, client/src/components/ProcessOrder.jsx, client/src/context/auth-context.jsx, client/src/pages/Pre-checkout/PreCheckout.jsx
Agregué el modal de procesar orden, si no hay usuario loggueado redirige a login, si hay un usuario loggeado, pero no tiene data de dirección de envío, redirige al precheckout, si ya tiene la data de dirección genera el botón de pago de mercado pago
Estaría faltando pobrar funcionalidad de firebase en la consola de firebase
=> Finish cart

client/src/components/Cart/Cart.jsx, client/src/components/Cart/Order.jsx, client/src/components/NavBarComp.jsx, client/src/context/auth-context.jsx, client/src/firebase/userDirectionBDD.js, client/src/pages/Pre-checkout/PreCheckout.jsx
Terminé componente de dirección adaptandolo a usuarios con direcciones ya registradas, faltan detalles de estilo
=> Direction user

Back/node_modules/jest/bin/jest.js, client/src/components/NavBarComp.jsx, client/src/pages/SignupPage/SignUpPage.jsx, client/src/pages/loginPage/loginPage.jsx, client/src/routes/AdminRoutes.jsx, client/src/routes/AppRouter.jsx, client/src/routes/AuthRoutes.jsx, client/src/routes/MainRouter.jsx, client/src/routes/index.js, client/src/store/slices/auth/authSlice.js, client/src/store/slices/auth/thunks.js
Routeo funcionando, reconocimiento de tipo de usuario una vez se loguea y lo manda a la página correspondiente, se crea el usuario en la base de datos de firebase para poder traer el rol en el logueo.
=> Router logic

client/src/components/Card/Card.jsx, client/src/pages/DetailPage.jsx
Agregue msj para cuando se agrega producto al carrito
=> Alert addProduct
